---
version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
    groups:
      go-modules:
        patterns:
          - "*"
  - package-ecosystem: gomod
    directory: /caddy
    schedule:
      interval: weekly
    commit-message:
      prefix: chore(caddy)
    groups:
      go-modules:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: ci
    groups:
      github-actions:
        patterns:
          - "*"
