---
version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
    groups:
      go-modules:
        patterns:
          - "*"
  - package-ecosystem: gomod
    directory: /caddy
    schedule:
      interval: weekly
    commit-message:
      prefix: chore(caddy)
    # These packages must be in sync with versions
    # used by github.com/caddyserver/caddy/v2
    ignore:
      - dependency-name: github.com/google/cel-go
      - dependency-name: github.com/quic-go/*
    groups:
      go-modules:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: ci
    groups:
      github-actions:
        patterns:
          - "*"
