name: Run tests locally

on: [push, pull_request]

jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.2']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          ini-file: development
          ini-values: display_errors=On,
          coverage: none
        env:
          phpts: ts
      - name: config
        run: |
          php -m
          php -i
      - name: Set include flags
        run: echo "CGO_CFLAGS=$(php-config --includes)" >> "$GITHUB_ENV"
      - name: Run library tests
        run: go test -race -v ./...
      - name: Run Caddy module tests
        working-directory: caddy/
        run: go test -race -v ./...
